[Match]
Distribution=fedora

[Content]
WithRecommends=false
RemovePackages=
    hyperv-daemons
    tailscale
    virtualbox-guest-additions

Packages=
    atop
    btop
    et
    fish
    htop
    incus-client
    intel-undervolt
    nebula
    nmap
    powertop
    python3-devel
    syncthing
    tuned-utils
    uv

EnableUnits=
    intel-undervolt
