[Match]
Distribution=fedora

[Build]
SandboxTrees=usr/share/dnf5/repos.d/netbird.repo:/etc/yum.repos.d/netbird.repo

[Distribution]
Repositories=netbird

[Content]
WithRecommends=false
Packages=
    netbird-ui
    libappindicator-gtk3
    libappindicator
